main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path("",views.homepage, name="homepage"),
    path("inventory", views.inventory, name="inventory"),
    path("profile", views.profile, name="profile"),
    path("stockyard", views.stockyard, name="stockyard"),
    path("forecasting", views.forecasting, name="forecasting"),
    path("reports", views.reports, name="reports"),
    path("stockyardprocessed", views.stockyardprocessed, name="stockyardprocessed"),
    path("stockyardsliced", views.stockyardsliced, name="stockyardsliced"),
    path("maps", views.maps, name="maps"),
    path("forecastinglime", views.forecastinglime, name="forecastinglime"),
    path("forecastingcoal", views.forecastingcoal, name="forecastingcoal"),
    path("new", views.new, name="new"),
    path("plan", views.plan, name="plan"),
    path("plansummary", views.plansummary, name="plansummary"),
    path("reports", views.reports, name="reports"),
    path("test", views.test, name="test"),
	path("report1", views.report1, name="report1"),
	path("report2", views.report2, name="report2"),
	path("report3", views.report3, name="report3"),
	path("report4", views.report4, name="report4"),
    
    
]

stockyard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from reportlab.pdfgen import canvas    
from django.http import HttpResponse

from azure.storage.blob import blockblobservice
from django.conf import settings as djangoSettings

from mimetypes import guess_type
from PIL import Image
import base64
import urllib.request
import io
import requests
import json
import os
#import matplotlib.pyplot as plt

# Create your views here.

def json_img(payload):
    scoring_uri = "<Replace-with-your-scoring_uri>"
    header = {"Content-Type": "application/json"}
    dd = json.dumps(payload)
    response = requests.post(scoring_uri,data=json.dumps(payload), headers=header, verify=False)
    result = response.text
    return result

def test(request):
        
    return render(request=request,
                  template_name = "main/test.html"
                  )   
    
def homepage(request):
 
    return render(request=request,
                  template_name = "main/login.html"
                  )
def inventory(request):
        
    return render(request=request,
                  template_name = "main/inventory.html"
                  )     
def stockyard(request):
        
    return render(request=request,
                  template_name = "main/stockyard.html"
                  )     
def profile(request):
        
    return render(request=request,
                  template_name = "main/profile.html"
                  )     
def reports(request):
        
    return render(request=request,
                  template_name = "main/reports.html"
                  )     
def plan(request):
        
    return render(request=request,
                  template_name = "main/plan.html"
                  )     
def forecasting(request):
        
    return render(request=request,
                  template_name = "main/forecasting.html"
                  )       
def stockyardsliced(request):
        
    return render(request=request,
                  template_name = "main/stockyardsliced.html"
                  )         

def maps(request):
        
    return render(request=request,
                  template_name = "main/maps.html"
                  )                  

def forecastinglime(request):
        
    return render(request=request,
                  template_name = "main/forecastinglime.html"
                  )

def forecastingcoal(request):
        
    return render(request=request,
                  template_name = "main/forecastingcoal.html"
                  )

def new(request):
        
    return render(request=request,
                  template_name = "main/new.html"
                  )                  
                  
def plansummary(request):
        
    return render(request=request,
                  template_name = "main/plansummary.html"
                  )
def reports(request):
        
    return render(request=request,
                  template_name = "main/reports.html"
                  )
				  
def report1(request):
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'attachment; filename="report1.pdf"'

	document_width, document_height = (600,700)
	
	path = "main/img/report1.png"
	
	Image_file = Image.open(path)
	
	image_width, image_height = Image_file.size
	image_aspect = image_height / float(image_width)
	
	print_width = document_width
	print_height = document_width * image_aspect
	
	p = canvas.Canvas(response)
	p.setFont('Times-Roman',18)
	p.drawString(170,750,"Report for stockpile ID SA-D-101")
	p.drawImage(path, document_width - print_width, document_height - print_height, width=print_width, height=print_height)
	
	p.save()
	return response
	
	
def report2(request):
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'attachment; filename="report2.pdf"'

	document_width, document_height = (600,750)
	
	path = "main/img/report2.png"
	
	Image_file = Image.open(path)
	
	image_width, image_height = Image_file.size
	image_aspect = image_height / float(image_width)
	
	print_width = document_width
	print_height = document_width * image_aspect
	
	p = canvas.Canvas(response)
	p.setFont('Times-Roman',18)
	p.drawString(170,750,"Report for stockpile ID SA-D-102")
	p.drawImage(path, document_width - print_width, document_height - print_height, width=print_width, height=print_height)
	
	p.save()
	return response
	

def report3(request):
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'attachment; filename="report3.pdf"'

	document_width, document_height = (600,750)
	
	path = "main/img/report3.png"
	
	Image_file = Image.open(path)
	
	image_width, image_height = Image_file.size
	image_aspect = image_height / float(image_width)
	
	print_width = document_width
	print_height = document_width * image_aspect
	
	p = canvas.Canvas(response)
	p.setFont('Times-Roman',18)
	p.drawString(170,750,"Report for stockpile ID SA-D-103")
	
	p.drawImage(path, document_width - print_width, document_height - print_height, width=print_width, height=print_height)
	
	p.save()
	return response
	

def report4(request):
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'attachment; filename="report4.pdf"'

	document_width, document_height = (600,750)
	
	path = "main/img/report4.png"
	
	Image_file = Image.open(path)
	
	image_width, image_height = Image_file.size
	image_aspect = image_height / float(image_width)
	
	print_width = document_width
	print_height = document_width * image_aspect
	
	p = canvas.Canvas(response)
	p.setFont('Times-Roman',18)
	p.drawString(170,750,"Report for stockpile ID SA-D-104")
	p.drawImage(path, document_width - print_width, document_height - print_height, width=print_width, height=print_height)
	
	p.save()
	return response

def stockyardprocessed(request):

    """account_name = '<Replace-with-your-account_name>'
    account_key = '<Replace-with-your-account_key>'
    path = "<Replace-with-the-path-to-your-container>"

    obj = blockblobservice.BlockBlobService(account_name,account_key)
    gen = obj.list_blobs(container_name='test')
    names = []
    prop = []
    for blob in gen:
        names.append(blob.name)
        prop.append(blob.properties.last_modified)
    latest = names[prop.index(max(prop))]
    path = path+latest""" ##FOR DYNAMIC IMAGE PROCESSING, USE THE ABOVE CODE AND COMMENT THE PATH BELOW

    path = "<Replace-with-the-path-to-your-image>"
    with urllib.request.urlopen(path) as url:
        f = io.BytesIO(url.read())
        path = base64.b64encode(f.read())
        img = path.decode('utf-8')
            
    #Change the hexColours as required
    hexColours = [["#140303", "#240004", "#630214", "#2d1014", "#3b0505"], ["#ded3d1", "#baaaad", "#9b837d", "#958389"], ["#110d0f", "#040101", "#0f0b08", "#090a0c", "#040404"]]
    diff = 40
    payload = [{"hexcolours": hexColours[0], "path": img, "diff": diff}, {"hexcolours": hexColours[1], "path": img, "diff": diff}, {"hexcolours": hexColours[2], "path": img, "diff": diff}]
    raw_materials = ["IronOre", "Limestone", "Coal"]
    
    #os.remove(djangoSettings.STATIC_ROOT+"/main/img/yard1.jpg")
    
    context = dict()
    for i in range(3):
        file = djangoSettings.STATIC_ROOT+"/main/img/"+raw_materials[i]+".png"
        #filenames[raw_materials[i]] = "main/img/"+raw_materials[i]+".png"
        os.remove(file)
        result = json_img(payload[i])
        fh=open(file, "wb")
        #fh = open(raw_materials[i]+".png", "wb")
        data = base64.b64decode(result)
        fh.write(data)
        fh.close()
        
        
        with open(file, "rb") as f:
            data = f.read()
 
        encoded = base64.b64decode(data)
        content_type, encoding = guess_type(file)
        context[raw_materials[i]] = data
        #.decode('utf-8').strip()
        #return "data:%s;base64,%s" % (content_type, encoded)
        
        """if(file_name!=latest):
        root_path = '<Replace-with-the-path-to-your-local-directory>'
        dir_name = 'images'
        path = f"{root_path}/{dir_name}"

        account_name = ''
        account_key = ''
        container_name = ''

        block_blob_service = blockblobservice.BlockBlobService(
            account_name=account_name,
            account_key=account_key
        )

        blob_name = f"{dir_name}/{file_name}"
        file_path = f"{path}/{file_name}"
        block_blob_service.create_blob_from_path(container_name, blob_name, file_path)"""
        """img=plt.imread(raw_materials[i]+".png")
        imgplot = plt.imshow(img)
        plt.show()""" ## TO UPLOAD GENERATED IMAGE TO AZURE CONTAINER

    return render(request=request,
                  template_name = "main/stockyardprocessed.html",
                  context = context
                  )                  

main/templates/main/maps.html
<!DOCTYPE html>
<html lang="en">

<head>
   <title>Stockyard Management Tool</title>
  {% load static %}
  <!-- Favicons -->
  <link href={% static "main/img/favicon.ico" %}rel="icon">
  <link href={% static "main/img/apple-touch-icon.png" %} rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href={% static "main/lib/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <!--external css-->
  <link href={% static "main/lib/font-awesome/css/font-awesome.css" %} rel="stylesheet" />
  <link type="text/css" href= {% static "main/css/zabuto_calendar.css" %} rel="stylesheet" >
  <link type="text/css" href= {% static "main/lib/gritter/css/jquery.gritter.css" %} rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href={% static "main/css/styles.css" %} rel="stylesheet" />
  <link href= {% static "main/css/style-responsive.css" %}rel="stylesheet" />
  <script src= {% static "main/lib/chart-master/Chart.js" %}></script>
  <script src={% static "main/lib/datetime.js" %}></script>

  
</head>

<body onload="datetime()">
  <section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
      <div class="sidebar-toggle-box">
        <div class="fa fa-bars tooltips" data-placement="right" data-original-title=" "></div>
      </div>
      <!--logo start-->
      <a href="{% url 'main:inventory' %}" class="logo"><b><span>STOCKYARD</span> MANAGEMENT TOOL&nbsp&nbsp&nbsp</b></a>
      <!--logo end-->
      
	    
       
    </header>
    <!--header end-->
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
          <p class="centered"><a href="{% url 'main:profile' %}"><img src= {% static "main/img/user.jpg" %} class="img-circle" width="80"></a></p>
          <h5 class="centered" style="color:white;font-family:arial">Welcome<br>Arthur Allan<br></h5>
		  <h6 class="centered" style="color:white;font-family:arial">Time: <span id="curtime"></span></h5>
		  <h6 class="centered" style="color:white;font-family:arial">Date: <span id="curdate"></span></h5>
          <br><br>
		  <ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <div class="row mt">
          <div class="col-sm-12">
            <section class="panel">
              <header class="panel-heading">
                Select your steel plant location
              </header>
              <div class="panel-body">
                <div id="controls-tabs"></div>
                <div id="info"></div>
                <div id="gmap-tabs"></div>
              </div>
            </section>
          </div>
		  <div class="col-sm-12" align="right">
		  <form action="{% url 'main:inventory' %}">
		  <button  type="submit" class="btn btn-primary">Apply</button>
		  </form>
		  </div>
        </div>
      </section>
  </section>
   
  
  <!-- js placed at the end of the document so the pages load faster -->  <!-- js placed at the end of the document so the pages load faster -->
  <script src={% static "main/lib/jquery/jquery.min.js" %} ></script>

  <script src= {% static "main/lib/bootstrap/js/bootstrap.min.js" %}></script>
  <script class="include" type="text/javascript" src= {% static "main/lib/jquery.dcjqaccordion.2.7.js" %}></script>
  <script src={% static "main/lib/jquery.scrollTo.min.js" %}></script>
  <script src={% static "main/lib/jquery.nicescroll.js" %} type="text/javascript"></script>
  <script src={% static "main/lib/jquery.sparkline.js" %}></script>
  
  <!--common script for all pages-->
  <script src={% static "main/lib/common-scripts.js" %} ></script>
  <script type="text/javascript" src={% static "main/lib/gritter/js/jquery.gritter.js" %}></script>
  <script type="text/javascript" src={% static "main/lib/gritter-conf.js" %}></script>
  
  <!--script for this page-->
 
  
  <script src="http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7"></script>
  <script src= {% static "main/lib/google-maps/maplace.js" %}></script>
  <script src={% static "main/lib/google-maps/data/points.js"%}></script>
  <script>
    //ul list example
   
    new Maplace({
      locations: LocsB,
      map_div: '#gmap-tabs',
      controls_div: '#controls-tabs',
      controls_type: 'dropdown',
      controls_on_map: false,
      show_infowindow: false,
      start: 1,
      afterShow: function(index, location, marker) {
        $('#info').html(location.html);
      }
    }).Load();
  </script>
    
</body>

</html>

main/templates/main/new.html
<html>
<body>
<input type="text" id="result" name="result">
<p>{{result.Ironore}}</p>
</body>
</html>

main/templates/main/reports.html
<!DOCTYPE html>
<html lang="en">

<head>
   <title>Stockyard Management Tool</title>
  {% load static %}
  <!-- Favicons -->
  <link href={% static "main/img/favicon.ico" %} rel="icon">
  <link href={% static "main/img/apple-touch-icon.png" %} rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href={% static "main/lib/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <!--external css-->
  <link href={% static "main/lib/font-awesome/css/font-awesome.css" %} rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href={% static "main/css/zabuto_calendar.css" %}>
  <link rel="stylesheet" type="text/css" href={% static "main/lib/gritter/css/jquery.gritter.css" %} />
  <!-- Custom styles for this template -->
  <link href={% static "main/css/styles.css" %} rel="stylesheet">
  <link href={% static "main/css/style-responsive.css" %} rel="stylesheet">
  <script src={% static "main/lib/chart-master/Chart.js" %}></script>
  <script src={% static "main/lib/datetime.js" %}></script>

  
</head>

<body onload="datetime();">
  <section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
      <div class="sidebar-toggle-box">
        <div class="fa fa-bars tooltips" data-placement="right" data-original-title=" "></div>
      </div>
      <!--logo start-->
     <a href="{% url 'main:inventory' %}" class="logo"><b><span>STOCKYARD</span> MANAGEMENT TOOL&nbsp&nbsp&nbsp</b></a>
      <!--logo end-->
      
	    
       <div class="top-menu">
	   <ul class="nav pull-right top-menu">
          <li><a class="reports" href="{% url 'main:homepage' %}">Logout</a></li>
        </ul>
	   <!-- <ul class="nav top-menu">
		  <li class="top">
		    <a class="pages" href="inventory.html"><i class="fa fa-truck"></i><span>&nbspIncoming Inventory</span></a>
          </li>
          <li class="top">
		    <a class="pages" href="stockyard.html"><i class="fa fa-picture-o"></i><span>&nbspMonitor Stockyard</span></a>
          </li>
		  <li class="top">
            <a class="pages" href="forecasting.html"><i class="fa fa-bar-chart-o"></i><span>&nbspMaterial Forecasting</span></a>
          </li>
		  <li class="top">
             <a class="active" class="pages" href="plan.html"><i class="fa fa-edit"></i><span>&nbspPlan & schedule</span></a>
          </li>
		  <li class="top">
             <a class="pages" href="reports.html"><i class="fa fa-book"></i><span>&nbspReports</span></a>
          </li>
        </ul>-->
       </div>
    </header>
    <!--header end-->
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
		<br>
        <ul class="sidebar-menu" id="nav-accordion">
          <p class="centered"><a href=""{% url 'main:profile' %}""><img src={% static "main/img/user.jpg" %} class="img-circle" width="80"></a></p>
          <h5 class="centered" style="color:white;font-family:arial">Welcome<br>Arthur Allan<br></h5>
		  <h6 class="centered" style="color:white;font-family:arial">Time: <span id="curtime"></span></h5>
		  <h6 class="centered" style="color:white;font-family:arial">Date: <span id="curdate"></span></h5>
          <br><br>
		 <li class="mt">
            <a href="#">
              <i class="fa fa-home"></i>
              <span>Overview</span>
              </a>
          </li>
		  <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-shopping-cart"></i>
              <span>Materials</span>
			   <i class="fa fa-caret-down" style="padding-left:67px"></i>
              </a>
            <ul class="sub">
              <li><a href="#">Iron</a></li>
              <li><a href="#">Coal</a></li>
			  <li><a href="#">Limestone</a></li>
            </ul>
          </li>
          <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-warning"></i>
              <span>Alerts</span>
			   <i class="fa fa-caret-down" style="padding-left:88px"></i>
              </a>
            <ul class="sub">
              <li><a href="#">Alarms</a></li>
              <li><a href="#">Warnings</a></li>
			  <li><a href="#">Delays</a></li>
            </ul>
          </li>
          <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-wrench"></i>
              <span>Action</span>
			  <i class="fa fa-caret-down" style="padding-left:86px"></i>
              </a>
            <ul class="sub">
               <li><a href="#">Run PP</a></li>
               <li><a href="#">Stop PP</a></li>
			   <li><a href="#">Edit PP</a></li>
			   <li><a href="#">Alternative PP</a></li>
            </ul>
          </li>
          <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-bar-chart-o"></i>
              <span>Analysis</span>
			   <i class="fa fa-caret-down" style="padding-left:72px"></i>
              </a>
            <ul class="sub">
               <li><a href="#">Planning analysis</a></li>
              <li><a href="#">Operational metrics</a></li>
			  <li><a href="#">Trend chart</a></li>
            </ul>
          </li>
            <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-question-circle"></i>
              <span>Help</span>
			   <i class="fa fa-caret-down" style="padding-left:95px"></i>
              </a>
            <ul class="sub">
               <li><a href="#">24/7 Tool support</a></li>
              <li><a href="#">Troubleshooting</a></li>
			  <li><a href="#">Instructions</a></li>
			   <li><a href="#">FAQs</a></li>
            </ul>
          </li>
         </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
          <div class="row" style="padding-left:30px">
		      <ul class="nav top-menu">
		  <li class="top">
		    <a class="pages" href="{% url 'main:inventory' %}"><img src={% static "main/img/inventory.ico" %} height="20px" width="25px"><span>&nbspIncoming Inventory</span></a>
          </li>
          <li class="top">
		    <a class="pages" href="{% url 'main:stockyard' %}"><i class="fa fa-eye"></i><span>&nbspMonitor Stockyard</span></a>
          </li>
		  <li class="top">
            <a class="pages" href="{% url 'main:forecasting' %}"><i class="fa fa-bar-chart-o"></i><span>&nbspMaterial Forecasting</span></a>
          </li>
		  <li class="top">
             <a class="pages" href="{% url 'main:plan' %}"><i class="fa fa-edit"></i><span>&nbspPlan & schedule</span></a>
          </li>
		  <li class="top">
             <a class="active" class="pages" href="{% url 'main:reports' %}"><i class="fa fa-book"></i><span>&nbspReports</span></a>
          </li>
        </ul>
		  </div>
		
		<div class="row">
		  <div class="col-lg-12" style="padding-top:20px;padding-bottom:30px;border-right:thin solid #A9A9A9;border-left:thin solid #A9A9A9;border-top:thin solid #A9A9A9">
		     <table id="reports" height="250px" width="250px">
			<tr>
			<th>Stockpile ID</th>
			<th>Material ID</th>
			<th>Tonnage(T)</th>
			<th>Value($)</th>
			<th>Date</th>
			<th>Authorized signatory</th>
			<th>Report</th>
			</tr>
			<tr onclick="document.getElementById('reportimg').src='{% static 'main/img/report1.png' %}';document.getElementById('rowdetail').innerHTML='Report for stockpile ID SA-D-101'" >
			<td>SA-D-101</td>
			<td>FE-103120</td>
			<td>45</td>
			<td>1488.48</td>
			<td>20-Feb-2020</td>
			<td>Ben Stokes</td>
			<td><a href="{% url 'main:report1' %}" download target="_Blank" rel="nofollow noopener" ><u>Download</u></a></td>
			</tr>
			<tr onclick="document.getElementById('reportimg').src='{% static 'main/img/report2.png' %}';document.getElementById('rowdetail').innerHTML='Report for stockpile ID SA-D-102'">
			<td>SA-D-102</td>
			<td>LMS-125607</td>
			<td>62</td>
			<td>988.43</td>
			<td>23-Feb-2020</td>
			<td>Kevin</td>
			<td><a href="{% url 'main:report2' %}" download target="_Blank" rel="nofollow noopener" ><u>Download</u></a></td>
			</tr>
			<tr onclick="document.getElementById('reportimg').src={% static 'main/img/report3.png' %};document.getElementById('rowdetail').innerHTML='Report for stockpile ID SA-D-103'">
			<td>SA-D-103</td>
			<td>C-1452370</td>
			<td>24</td>
			<td>356.56</td>
			<td>04-Mar-2020</td>
			<td>John holland</td>
			<td><a href="{% url 'main:report3' %}" download target="_Blank" rel="nofollow noopener" ><u>Download</u></a></td>
			</tr>
			<tr onclick="document.getElementById('reportimg').src={% static 'main/img/report4.png' %};document.getElementById('rowdetail').innerHTML='Report for stockpile ID SA-D-104'">
			<td>SA-D-104</td>
			<td>C-1460345</td>
			<td>38</td>
			<td>497.45</td>
			<td>14-Mar-2020</td>
			<td>John holland</td>
			<td><a href="{% url 'main:report4' %}" download target="_Blank" rel="nofollow noopener" ><u>Download</u></a></td>
			</tr>
			</table>
		  </div>
        </div>		  
		<div class="row">
		  <div class="col-lg-12" style="padding-top:35px;border-bottom:thin solid #A9A9A9;border-left:thin solid #A9A9A9;border-right:thin solid #A9A9A9;border-top:thin solid #A9A9A9">
		    <span id="rowdetail" style="color:black;font-size:15px;" ><center>Report for stockpile ID SA-D-101</center></span>
			<img src={% static "main/img/report1.png" %} id="reportimg" height="350px" width="100%">
		  </div>
        </div>		  
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
      </section>
    </section>
    <!--main content end-->
    
  </section>
  <!-- js placed at the end of the document so the pages load faster -->
  <script src={% static "main/lib/jquery/jquery.min.js" %}></script>

  <script src={% static "main/lib/bootstrap/js/bootstrap.min.js" %}></script>
  <script class="include" type="text/javascript" src={% static "main/lib/jquery.dcjqaccordion.2.7.js" %}></script>
  <script src={% static "main/lib/jquery.scrollTo.min.js" %}></script>
  <script src={% static "main/lib/jquery.nicescroll.js" %} type="text/javascript"></script>
  <script src={% static "main/lib/jquery.sparkline.js" %}></script>
  <!--common script for all pages-->
  <script src={% static "main/lib/common-scripts.js" %}></script>
  <script type="text/javascript" src={% static "main/lib/gritter/js/jquery.gritter.js" %}></script>
  <script type="text/javascript" src={% static "main/lib/gritter-conf.js" %}></script>
  <!--script for this page-->
  <script src={% static "main/lib/sparkline-chart.js" %}></script>
  <script src={% static "main/lib/zabuto_calendar.js" %}></script>
  
    
</body>

</html>

main/templates/main/test.html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <script type="text/javascript">
        window.onload = function () {
            //Build an array containing Customer records.
            var customers = new Array();
            customers.push(["John Hammond", "United States"]);
            customers.push(["Mudassar Khan", "India"]);
            customers.push(["Suzanne Mathews", "France"]);
            customers.push(["Robert Schidner", "Russia"]);
 
            //Add the data rows.
            for (var i = 0; i < customers.length; i++) {
                AddRow(customers[i][0], customers[i][1]);
            }
        };
 
        function Add() {
            var txtName = document.getElementById("txtName");
            var txtCountry = document.getElementById("txtCountry");
            AddRow(txtName.value, txtCountry.value);
            txtName.value = "";
            txtCountry.value = "";
        };
 
        function Remove(button) {
            //Determine the reference of the Row using the Button.
            var row = button.parentNode.parentNode;
            var name = row.getElementsByTagName("TD")[0].innerHTML;
            if (confirm("Do you want to delete: " + name)) {
 
                //Get the reference of the Table.
                var table = document.getElementById("tblCustomers");
 
                //Delete the Table row using it's Index.
                table.deleteRow(row.rowIndex);
            }
        };
 
        function AddRow(name, country) {
            //Get the reference of the Table's TBODY element.
            var tBody = document.getElementById("tblCustomers").getElementsByTagName("TBODY")[0];
 
            //Add Row.
            row = tBody.insertRow(-1);
 
            //Add Name cell.
            var cell = row.insertCell(-1);
            cell.innerHTML = name;
 
            //Add Country cell.
            cell = row.insertCell(-1);
            cell.innerHTML = country;
 
            //Add Button cell.
            cell = row.insertCell(-1);
            var btnRemove = document.createElement("INPUT");
            btnRemove.type = "button";
            btnRemove.value = "Remove";
            btnRemove.setAttribute("onclick", "Remove(this);");
            cell.appendChild(btnRemove);
        }
    </script>
    <table id="tblCustomers" cellpadding="0" cellspacing="0" border="1">
        <thead>
            <tr>
                <th>Name</th>
                <th>Country</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
        <tfoot>
            <tr>
                <td><input type="text" id="txtName" /></td>
                <td><input type="text" id="txtCountry" /></td>
                <td><input type="button" onclick="Add()" value="Add" /></td>
            </tr>
        </tfoot>
    </table>
</body>
</html>